package com.DougFSiva.checkMate.websocket;

public enum TipoMensagemWebsocket {

	CHECKLIST_AMBIENTE_ABERTO,
	CHECKLIST_AMBIENTE_LIBERADO,
	CHECKLIST_AMBIENTE_ENCERRADO,
	CHECKLIST_AMBIENTE_DELETADO,
	CHECKLIST_COMPARTIMENTO_ENTRADA_PREENCHIDO,
	CHECKLIST_COMPARTIMENTO_SAIDA_PREENCHIDO,
	OCORRENCIA_ABERTA,
	OCORRENCIA_TRATADA,
	OCORRENCIA_ENCERRADA,
	EMPRESTIMO_REALIZADO,
	EMPRESTIMO_DEVOLVIDO

}
